# Generated by Django 3.1 on 2020-08-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='category',
            field=models.CharField(choices=[('Horror', 'Horror'), ('Scifi', 'Scifi'), ('Action', 'Action'), ('Adventure', 'Adventure'), ('Fantasy', 'Fantasy')], max_length=50),
        ),
    ]
