# Generated by Django 3.1 on 2020-08-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200813_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='rating',
            field=models.IntegerField(choices=[('Horror', 'Horror'), ('Scifi', 'Scifi'), ('Action', 'Action'), ('Adventure', 'Adventure'), ('Fantasy', 'Fantasy')]),
        ),
    ]
